preset: laravel

risky: false

enabled:
  - blank_line_after_namespace
  - cast_spaces
  - short_array_syntax
  - no_whitespace_in_blank_lines
  - no_unused_imports
  - no_useless_return
  - no_useless_else
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - unalign_equals