language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml